### PR TITLE
Weapons Rotation bug

### LINKED ISSUE #210: Weapons Rotating
## Description
Currently, the weapons in the world are rotating and following the mouse movement. This is something we want for the chosen weapon so that we can correctly direct the laser where we want, but we don't want it for the rest of the weapons. The issue is that all the weapons that have been spawned on the ground and not picked up, are rotating, when they should be staying still and static on the ground.

## How To Reproduce
Steps to reproduce the behaviour:
1. Start the game
2. Watch the weapons
3. Move your mouse around on the screen
4. See the weapons following your mouse rotation.

## Expected Behaviour
We want the weapons to lie still on the ground when they are not selected. And that the selected and used weapon will be able to rotate according to the mouse movement, so that we can aim the direction we want.

## Additional Context
We believe that what we might need to do to fix the problem is add textures to the world, but not the actual weapons entities.

## Temporary Fix
We want to try and create a PickupableItem Factory that spawns the textures in the world and on to the map, and not the actual weapon entities which is what it is currently doing. We then want to create the actual weapons when the item is picked up and placed in the inventory. This way we will have actual weapons in the inventory, but only textures on the map to make them static.

### PR DESCRIPTION
**Pull request by helleengebakken**
# Description

This PR fixes the bug where all weapons placed in the world rotate with the mouse cursor, even when they are just lying on the ground. There is now a clear separation between:

- World pickups: non-rotating textures used only for being seen and picked up.
- Inventory/equipped weapons: fully featured weapon entities (with rotation/behaviour) created only when a pickup is collected.

Fixes / Closes #210 

### ItemPickUpComponent

- **pickUpItem()**: reads the pickup’s ItemComponent.texture, creates a proper weapon via `WeaponsFactory` (weaponFromTexture()), adds the weapon to the inventory, and disposes the world pickup shell.
- **onDropFocused()**: removes the focused inventory weapon and respawns a world pickup shell using `WorldPickUpFactory.createPickupFromTexture(tex)`. 

### ItemSpawner

- **ItemSpawner.makeItem()** now creates world pickup shells via `WorldPickUpFactory.createWeaponPickup(Weapons)` so spawned map items no longer rotate with the mouse.

- [x] Bug fix (non-breaking change which fixes an issue)

- [x] This change needs documentation updates in wiki

# How Has This Been Tested?

### Unit tests
`ItemPickUpComponentTest.pickUpAddsItemAndClearsTarget`
- Uses ResourceService (textures) and PhysicsService.
- Creates a world pickup shell with ItemComponent.texture = images/pistol.png.
- Triggers "pick up" → inventory receives a new weapon entity (not the shell), and targetItem clears.

### Manual testing

1. Start a map with items on the ground.
2. Move the mouse around: world items do not rotate.
3. Walk to an item and press E:
4. Item disappears from world.
5. Inventory gains the weapon (now rotates when actually equipped/used).
6. Press R on a focused slot:
7. Inventory item is removed.
8. A non-rotating pickup shell appears slightly offset at the player’s feet.

# Checklist:

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my code

- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] New and existing unit tests pass locally with my changes

- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: source/core/src/main/com/csse3200/game/entities/factories/items/WorldPickUpFactory.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+                type.getConfig().weaponType == com.csse3200.game.entities.configs.ItemTypes.MELEE
+                        ? ItemTypes.MELEE : ItemTypes.RANGED);
+
+        pickup.getComponent(PhysicsComponent.class).setBodyType(BodyDef.BodyType.StaticBody);
+        return pickup;
+    }
+
+    /**
+     * Build from texture when dropping
+     * */
```
Comment (cailindelgado) [inline source/core/src/main/com/csse3200/game/entities/factories/items/WorldPickUpFactory.java:35]: the Extra '*' 😭

**Review by cailindelgado — CHANGES_REQUESTED** [review]
Looks good, looks formatted, however the player cannot shoot now? Could you check that out please

**Review by keys-i — APPROVED** [review]
LGTM
